### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-playground#18]
https://www.reddit.com/r/d2lang/comments/zrj6ip/please_add_dark_mode_to_the_playground_that_would/

**Comment by alixander** [comment]
design:

![1280 - dark mode](https://github.com/terrastruct/d2-playground/assets/3120367/76d1f509-2c17-4f12-8e41-3348561c46b1)

**Comment by Silverbullet069** [comment]
Keep using Dark Reader, paste this code into your `userContent.css` file:

```css
@-moz-document domain(play.d2lang.com) {
  /* NOTE: works alongside Dark Reader*/

  /* TODO: change cursor color as well */

  .text.fill-N1,
  .text-bold.fill-N1 {
    mix-blend-mode: difference !important;
  }

  .text-italic.fill-N1,
  .text-italic.fill-N2 {
    fill: #fff !important;
  }

  /* Latex */
  g[data-mml-node="math"] {
    color: #000 !important;
  }

  /* SVG images */
  /* .stroke-B1.fill-N7 */
  [href^="data:image/svg+xml"] {
    filter: invert(100%) sepia(0%) saturate(26%) hue-rotate(88deg) brightness(105%) contrast(108%) !important;
    mix-blend-mode: difference !important;
  }

  /* SQL schema */
  .sketch-overlay-N1 {
    mix-blend-mode: overlay !important;
    fill: #000 !important;
  }

  /* Class diagram */
  .text-mono.fill-N1 {
    fill: #0A0F25 !important;
  }
}
```

Of course, d2 supports custom styling, but the playground's UI is white and we want that to be dark mode as well. So disable Dark Reader is a no-go.
BUT, Dark Reader will change d2 compiled components' color on web so it will incorporate inconsistency with exported diagram if you meddle with custom styling. So, custom styling shouldn't be used at all. That's fine by me, fine-grained diagram tweaking can take a lot of time for nothing, default is always the better.
